baseURL = "https://reachaaut.github.io/ReachAAUt-Site/"
languageCode = "en-us"
title = "#ReachAAUt"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_og_title = "Hugo Hero Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Resources"
	url = "/resources/"
    weight = 1

[[menu.main]]
    name = "Cases"
    url = "/cases/"
    weight = 2

[[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"